# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarstvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lek', models.CharField(max_length=150, verbose_name='Наименование')),
                ('price_lek', models.IntegerField(verbose_name='цена')),
                ('apteka_adress', models.TextField(verbose_name='Адрес аптеки')),
            ],
        ),
    ]
