# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lekarstvo', '0003_lekarstvo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lekarstvo',
            old_name='apteka_adress',
            new_name='apteka_address',
        ),
    ]
