# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dj_Learn_start', '0002_auto_20170827_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_create'], 'verbose_name': 'Запись в блоге', 'verbose_name_plural': 'Записи в блоге'},
        ),
        migrations.AddField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата комментария'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Введите наименование лекарства '),
        ),
    ]
